oauthClient:
  redirectUris:
    - http://localhost:3000/authorization-code/callback
  applicationType: web
trustedOrigins:
  - http://localhost:3000/

directions: |+2
  Okta configuration written to: .okta.env

  Sign into Okta and update your Okta application to enable Refresh Token
  
  Install the dependencies using npm:

      npm install

  Run this application with:

      npm start
